name: action_kernel


on:
  workflow_dispatch:


jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download clang & kernel source
        run: |
          git clone https://gitlab.com/jjpprrrr/prelude-clang.git clang --depth=1
          git clone https://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@github.com/Xirudly/kernel_xiaomi_sm8150 -b crux kernel --depth=1
          
      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER="Kuriyama"
          export KBUILD_BUILD_HOST="Crux-Kernel"
          export PATH=$GITHUB_WORKSPACE/clang/bin:${PATH}
          args="                  O=out \
                                  ARCH=arm64 \
                                  SUBARCH=arm64 \
                                  CC=clang \
                                  LD=ld.lld \
                                  LLVM=1 \
                                  LLVM_IAS=1 \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=$GITHUB_WORKSPACE/clang/bin/aarch64-linux-gnu- \
                                  CROSS_COMPILE_COMPAT=$GITHUB_WORKSPACE/clang/bin/arm-linux-gnueabi- "
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          make ${args} crux_defconfig && make -j$(nproc --all) ${args}
          
      - name: Package kernel
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/Xirudly/AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          cp kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp kernel/out/arch/arm64/boot/dtbo.img AnyKernel3/
          zip -r XTKernel-crux.zip AnyKernel3/*
          
      - name: Upload kernel
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Kuriyama-crux.zip"
          tag: "Kuriyama-crux-20240701"
          token: ${{ secrets.GITHUB_TOKEN }}
